version: '3'

services:

  wiki:
    image: ghcr.io/gesinn-it-pub/openresearch-stack:dev
    ports:
      - ${WIKI_PORT:-80}:80
    volumes:
      - ./backstop/backstop_data:/var/www/html/backstop
    environment:
      - WIKI_DOMAIN
      - WIKI_PORT
      - ELASTICSEARCH_HOST=elasticsearch
      - MYSQL_HOST

  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker
  elasticsearch:
    image: elasticsearch:6.8.23
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: database
    profiles:
      - mysql

  backstop:
    image: backstopjs/backstopjs:6.0.4
    volumes:
      - ./backstop:/src
    links:
      - "wiki:wiki.local"
    profiles:
      - no-profile
