#!/bin/bash
EXTENSION=$1
VERSION=$2
EXTENSION_URL_PATH=$3

EXTENSION_URL=https://gitlab.com/$EXTENSION_URL_PATH/-/archive/$VERSION/$EXTENSION-$VERSION.tar.gz

get-extension.sh $EXTENSION $EXTENSION_URL
